### ISSUE TITLE
Why not use HEC query string auth?

### ISSUE THREAD

**Issue by zingagent** [splunk/zoom-webhook-to-hec#1]
The JWT addon method and this lambda proxy method seem overly complicated.  
Lets assume I've misunderstood something and hopefully you can tell me where my method for getting Zoom data in via Webhook to HEC below is wrong.

1. Create HEC token for zoom with query string auth
inputs.conf

[http://hec-app-zoom]
disabled = 0
token = goes-here
description = Receiver for Zoom webhook
index = zoom
indexes = zoom
sourcetype= zoom:webhook
**allowQueryStringAuth = true**

I found that Splunk was setting the time wrong (choosing the wrong field) on some events from Zoom so:
props.conf

[http://hec-app-zoom]
DATETIME_CONFIG = CURRENT

2. Setup Webhook in Zoom with url:
https://my-hec-service/services/collector/raw?token=goes-here

The authorisation is done within the url.
The authorisation header sent by Zoom is ignored by Splunk HEC, because we are doing query string auth with our HEC token.

I've had this running since April 3.

**Comment by zingagent** [comment]
As an aside, I use this same method to get other things like status page updates into Splunk via Webhook.
eg: go to status.victorops.com and subscribe to updates using webhook with a splunk hec url using a query string auth token.

If I'm doing it wrong, I really want to know.

**Comment by ryanwoconnor** [comment]
Great question and thanks for keeping me honest here! There are multiple ways to handle this. In this case we had requirements like using additional security features as shown in this blog https://www.splunk.com/en_us/blog/tips-and-tricks/getting-github-data-with-webhooks-part-2.html. You're not doing it wrong by any means. Serverless functions just allow for a little bit more control of the data.

**Comment by l00py** [comment]
The latest Zoom Webhook integration must support the url endpoint validation via challenge-response requests and event signature verification. The former is not natively supported by HEC, therefore a "middleware" is required.
