### ISSUE TITLE
Add support for Webhook Validation

### ISSUE THREAD

**Issue by stboch** [splunk/zoom-webhook-to-hec#2]
October of this year zoom will require all webhooks to validate based on a response to a specific message every 72 hours, it appears the current function lacks this ability.
https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint

**Comment by l00py** [comment]
@stboch, apologies for the delay. Feel free to give it a go.

**1.1.0 (June 2023)**
- Support for [Zoom Challenge-Response Check (CRC)](https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint)
- Zoom event verification using the latest [Zoom's header method](https://developers.zoom.us/docs/api/rest/webhook-reference/#verify-webhook-events)
